# Generated by Django 6.1.1 on 2026-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='nome_item',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
