# Generated by Django 6.1.1 on 2026-09-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_itempedido_nome_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='nome_item',
        ),
    ]
